name: Android CD

on:
  push:
    branches: [master, rel/*, ndk-test]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache (NDK)
      uses: actions/cache@v2
      with:
        path: ${ANDROID_HOME}/sdk/ndk/21.0.6113669
        key: ndk-cache-21.0.6113669
    - name: Build with Gradle
      run: sudo ./gradlew  --no-daemon clean bundleStage
    - name: Save Artifact
      uses: actions/upload-artifact@v1
      with:
        name: stage_bundle.aab
        path: "app/build/outputs/bundle/stageRelease/app-stage-release.aab"
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate ChangeLog
        run: |
          echo "Change Log TopLevelNumber: $GITHUB_RUN_ID, Workflow: $GITHUB_RUN_NUMBER, Action No: $GITHUB_ACTION" >> CHANGELOG.md
      - name: Save Artifact
        uses: actions/upload-artifact@v1
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md
  appcenter_release:
    runs-on: ubuntu-latest
    needs: [build, changelog]
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run Npm Install
        run: npm install
      - name: Distribute to AppCenter
        env:
          APPCENTER_TOKEN: "${{ secrets.APPCENTER_TOKEN }}"
        run: "npx appcenter distribute groups publish -f stage_bundle.aab -R CHANGELOG.md -a shrikanth_kr-g6qm/EM-Stage -g Collaborators --token $APPCENTER_TOKEN"


